### ISSUE TITLE
Add documentation for setup and contribution

### ISSUE THREAD

**Issue by kautukkundan** [GeekBoySupreme/TabTrum#4]
Hey, It'll be super helpful if we can have a small text about how to set up the project and also about the contribution guidelines

**Comment by GeekBoySupreme** [comment]
Hey @kautukkundan 
The documentation for Setup is given in the image in Readme itself.
Please find the contribution guidelines here - https://github.com/GeekBoySupreme/TabTrum/blob/master/Contributing.md
