### ISSUE TITLE
Add Protocol before external URL in README

### ISSUE THREAD

**Issue by aashutoshrathi** [GeekBoySupreme/TabTrum#5]
The Beta release URL in readme is added like `<a href='bit.ly/tabtrumbeta'>bit.ly/tabtrumbeta</a>` which needs to be changed to `<a href='https://bit.ly/tabtrumbeta'>bit.ly/tabtrumbeta</a>`. So that it doesn't redirect users to https://github.com/GeekBoySupreme/TabTrum/blob/master/bit.ly/tabtrumbeta (404).

**PS: Would recommend you (@GeekBoySupreme) to push a commit all by yourself ASAP, so that no one claims it for free Tee :wink:**

**Comment by GeekBoySupreme** [comment]
Thanks for pointing this out buddy. Had missed rectifying this. 
But this is a legit issue. If anyone notices and does a PR, wouldn't really be bad.

**Comment by GeekBoySupreme** [comment]
Done. Fixed this.
